### ISSUE TITLE
Username config support

### ISSUE THREAD

**Issue by totherik** [krakenjs/confit#12]
Consider adding support for username-based config using https://github.com/sindresorhus/username

**Comment by pvenkatakrishnan** [comment]
so something like `NODE_USERNAME='janedoe' , then `janedoe.json` applies as an override on top of `<env>.json` and default `config.json` ?

**Comment by jasisk** [comment]
If I'm understanding the proposal correctly, arbitrary envs *are* supported.

**Comment by pvenkatakrishnan** [comment]
yes, but in the form of `NODE_ENV=<something>.json`. The original proposal is saying look for `$USER` and override any configs with that username... for example:
if `USER`  is `janedoe`, automatically look for `janedoe.json` and apply overrides.

**Comment by aredridel** [comment]
Yeah, that proposal sounds problematic and a little too magical. It's conflating two namespaces that may have collisions.

**Comment by pvenkatakrishnan** [comment]
seems to me like we can close this one out.

**Comment by pvenkatakrishnan** [comment]
ups closed by mistake

**Comment by pvenkatakrishnan** [comment]
im closing this out, coz,
1. very old
2. as it seems like mostly views are against it. 
Reopen if disagree.
