### ISSUE TITLE
Make `import` protocol resolve before every config file merge

### ISSUE THREAD

**Issue by pvenkatakrishnan** [krakenjs/confit#26]
details in this thread https://github.com/krakenjs/kraken-js/issues/328

**Comment by totherik** [comment]
In reality [these](https://github.paypal.com/ertoth/three-sixty/) don't [have](https://github.com/krakenjs/confit/blob/b92c94c4f605ac1f2ea90bf60f41f0cf0eb187b8/index.js#L211) to happen synchronously to keep this API, the can just contribute to a Promise chain that is resolved at create time.

**Comment by pvenkatakrishnan** [comment]
this is the part that becomes more important with the enhancement really

https://github.com/krakenjs/confit/blob/b92c94c4f605ac1f2ea90bf60f41f0cf0eb187b8/index.js#L238

**Comment by pvenkatakrishnan** [comment]
Because https://github.com/krakenjs/confit/blob/b92c94c4f605ac1f2ea90bf60f41f0cf0eb187b8/index.js#L247

**Comment by totherik** [comment]
Still can easily be adapted to use the same mechanism.

**Comment by pvenkatakrishnan** [comment]
so something like
```
  confit(basedir).then(function(conf) {
      conf.create(function(err, config) {
             ...
             ...
     }
  }
```

**Comment by totherik** [comment]
Nope, the api doesn't need to change. Example forthcoming.

**Comment by pvenkatakrishnan** [comment]
available here https://github.com/krakenjs/confit/tree/es6 and soon to be published as 2.0

**Comment by pvenkatakrishnan** [comment]
2.0 published with the support.

**Comment by skoranga** [comment]
Any plan of updating kraken to use this? https://github.com/krakenjs/kraken-js/blob/v1.0.x/package.json#L76

**Comment by pvenkatakrishnan** [comment]
good question for discussion. Not completely opted out but was originally scheduled to be bumped with kraken 2.0
https://github.com/krakenjs/kraken-js/issues/324

**Comment by jasisk** [comment]
Yes, this change is intended for the next kraken release.
