### ISSUE TITLE
path not resolving correctly (gets resolver function instead of resolved val)

### ISSUE THREAD

**Issue by melbourne2991** [krakenjs/confit#30]
I worked out that if I "config.get" myobj it returns with "unresolved" as the resolving function.

myobj {
  unresolved: "path:./mypath"
}

In some situations it would be nice to resolve all unresolved functions on an object.

something like config.resolve('myobj')

Would this be within the scope of confit?

**Comment by melbourne2991** [comment]
Ok now i'm thinking this is a bug,

Looks like even when I reference myobj:unresolved directly (config.get('myobj:unresolved') I'm still getting the resolver function instead of the actual value..

**Comment by melbourne2991** [comment]
Ok so I worked it out.

the _path function in the shortstop lib returns a function where as other such as env don't. any particular reason for this? would be good if the api was more consistent

**Comment by totherik** [comment]
> the _path function in the shortstop lib returns a function where as other such as env don't. 

The others, sure do. [env included](https://github.com/krakenjs/shortstop-handlers/blob/069771241e4fb2203d71af14bcdd8497cd2ac2c5/index.js#L96). All [exported properties](https://github.com/krakenjs/shortstop-handlers/blob/069771241e4fb2203d71af14bcdd8497cd2ac2c5/index.js#L193-L201) for `shortstop-handlers` are handler factories.

Is it fair to assume this was caused as a result of the documentation error for which you submitted the PR?

**Comment by jasisk** [comment]
To demonstrate @totherik point:

##### index.js
``` js
var handlers = require('shortstop-handlers');
var config = require('confit');
var path = require('path');

var opts = {
  basedir: path.join(__dirname, 'config'),
  protocols: {
    path: handlers.path(),
    glob: handlers.glob(),
    file: handlers.file()
  }
};

config(opts).create(function (err, config) {
  console.log(config.get('handlers'));
});
```
---
##### config/config.js
``` json
{
  "handlers": {
    "filepath": "path:./config",
    "glob": "glob:./config/*.json",
    "file": "file:index.js"
  }
}
```
---
##### output
``` js
{ file: <Buffer 2f 2a e2 94 80 e2 ... >,
  filepath: '/Path/to/tmp/confit-test/config',
  glob: [ '/Path/to/tmp/confit-test/config/config.json' ] }
```

**Comment by melbourne2991** [comment]
@totherik yep just a documentation issue in the end cheers

**Comment by totherik** [comment]
Great, thanks for following up!
