### ISSUE TITLE
Cannot find module 'babel-runtime/helpers'

### ISSUE THREAD

**Issue by tkambler** [krakenjs/confit#39]
Confit is broken at the moment (for me). Error:

```
Cannot find module 'babel-runtime/helpers'
```

**Comment by totherik** [comment]
Looks like the babel deps are inverted. `babel` should be a devDependency, while `babel-runtime` should be a regular dependency.

**Comment by pvenkatakrishnan** [comment]
published 2.0.2 with the correct dependencies

**Comment by totherik** [comment]
I just installed 2.0.2 and verified it works.

**Comment by AprilArcus** [comment]
I am getting the same error in webpack / babel-loader. 4.7.3 is the last working version for me.

**Comment by totherik** [comment]
Babel doesn't play well with semver ranges (e.g. ^ and ~). We need to pin the deps to exact, specific versions. :/

**Comment by sebmck** [comment]
@totherik Yes, the `babel-runtime` version and the version of `babel` that compiled the files needs to be the same. See babel/babel#965.

**Comment by totherik** [comment]
Yep, I learned the hard way on another module. Is that documented somewhere such that I can share it with other developers?

**Comment by totherik** [comment]
confit@2.0.3 has been published with a pinned dependency on babel@4.7.3. Hopefully this resolves this issue.
