### ISSUE TITLE
Issue with unit test (or confit) isolation

### ISSUE THREAD

**Issue by grawk** [krakenjs/confit#44]
While developing a feature PR for confit, I came across an interesting problem. By simply adding a valid unit test to confit-test.js:

``` javascript
t.test('override with stringified number as env variable', function (t) {
        var factory;
        var env = process.env;

        process.env = {
            NODE_ENV: 'test',
            nested: '2001',
            override: '8000'
        };
        console.log(process.env);
        factory = confit(path.join(__dirname, 'fixtures', 'defaults'));
        factory.create(function (err, config) {
            t.error(err);
            t.ok(config);
            t.equal(config.get('nested'), '2001');
            t.equal(config.get('override'), '8000');

            t.end();
        });

        t.on('end', function () {
            process.env = env;
        });

    });
```

I caused another valid unit test "precedence" to fail.

I'm not sure what's going on but commenting out either "precedence" or "override with ..." test will allow the other to pass.

**Comment by grawk** [comment]
Also, if the tests are not adjacent to each other in the file, they both pass. If they are adjacent, and I wrap the second test in `process.nextTick` both of them pass.

This is on the 2.x branch. I wonder if the ES6 conversion has anything to do with this.

**Comment by grawk** [comment]
After further investigation, I've found that the `t.on('end', Function)` event handlers are firing out of sequence. The subsequent test is beginning before the current 'end' event fires. Since the statements in the 'end' event could just as easily be written inline prior to `t.end()`, this would fix the issue.

E.g. the test I pasted above would be rewritten as follows:

``` javascript
t.test('override with stringified number as env variable', function (t) {
        var factory;
        var env = process.env;

        process.env = {
            NODE_ENV: 'test',
            nested: '2001',
            override: '8000'
        };
        console.log(process.env);
        factory = confit(path.join(__dirname, 'fixtures', 'defaults'));
        factory.create(function (err, config) {
            t.error(err);
            t.ok(config);
            t.equal(config.get('nested'), '2001');
            t.equal(config.get('override'), '8000');
            process.env = env;
            t.end();
        });
    });
```

other tests can be changed similarly.

As far as the root cause, I have done some digging here: https://github.com/substack/tape

There are no issues filed that match this description. But, also, there is no documented event handling pattern as I see in the confit test suite. Not sure if we are either using some undocumented feature, or what... Rather than get lost down that rathole, I'll submit a PR which does away with `t.on('end', Function)`

**Comment by jasisk** [comment]
So what's happening here is the parent test binds a listener on the child's `end` before running the test. In this case, inside the body of the child test, a new listener is appended. So now you've got two listeners on the child test's `end`, the first of which runs the next test, the second of which repairs `process.env`.

**Comment by grawk** [comment]
All good in the hood.
