### ISSUE TITLE
Create separated handlers for config and import

### ISSUE THREAD

**Issue by jonathansamines** [krakenjs/confit#59]
Hi all, I was wondering if the `config` and `import` handlers could be moved as separated shortstop handlers?

**Comment by shaunwarman** [comment]
Hey @jonathansamines 

Sorry for the late reply. Are you using version `^2`? You can see the available handlers here:
https://github.com/krakenjs/confit#shortstop-handlers

**Comment by jonathansamines** [comment]
Yes, my suggestion was to extract both handlers either to the "shorstop-handlers" project or as a separated project with those handlers. Right now I am trying to use both of them without having to use "confit" itself.

**Comment by grawk** [comment]
`config` and `import` need to be separately considered in the config resolution lifecycle. It is not clear how you would abstract their functionality into `shortstop-handlers`
